name: "Asana Git"
description: "Asana Github Actions"
inputs:
  asana-pat:
    description: "Asana Public Access Token."
    required: true
  task-comment:
    description: "Provide text, which will add a comment with the pull request link to the asana task."
    required: false
branding:
  icon: "chevron-right"
  color: "gray-dark"
runs:
  using: "node12"
  main: "index.js"
